### ISSUE TITLE
Create specialize complete hook for sysprep

### ISSUE THREAD

**Issue by pnikonowicz** [GoogleCloudPlatform/compute-image-windows#110]
It would be nice to be able to be notified that the sysprep specialize task is completed so that I can add additional setup steps for my provisioned VM. 

The idea is to place the hook [here](https://github.com/GoogleCloudPlatform/compute-image-windows/blob/master/sysprep/instance_setup.ps1#L279) in the form of a file that is execute either as a powershell script.

**Comment by adjackura** [comment]
It looks like your talking about running a script at the end of instance setup, You can use a startup script to run at each boot:
https://cloud.google.com/compute/docs/startupscript#providing_a_startup_script_for_windows_instances

**Comment by pnikonowicz** [comment]
I'll check if that will work. I would like to provide a little more context. 

We have a service that can only run once.
We install the service.  
We then manually run GCE sysprep. 

We expect our service to only run once.

But what we see is our service is killed because of the required restart that GCE sysprep uses to bootstrap it's specialize task. 

Does this makes sense as a description for what we are trying to accomplish?

**Comment by adjackura** [comment]
I think I understand what your trying to do, just a few questions:
Is this a Windows service you install? If it is is there a reason its a service? A 'run only once' command doesnt seem to make much sense as a service.
What prevents it from running more than once in normal circumstances? Will it remove itself once it finishes whatever it does? 

Is there anything else you install before running sysprep? Could you just move all these commands to a sysprep-specialize-script-ps1 metadata script? It will only run during that initial instance setup, and you wouldn't need to create a custom image.

**Comment by pnikonowicz** [comment]
It is an actual service but it can only be started once. We have a work around though. We lowered the start priority of our service on windows by setting it to "Delayed Auto Start". This allows the GCP sysprep to finish and not kill our service while it is starting up. 

This is no longer an issue for us. Thank you for your attention.
