### ISSUE TITLE
Failed activation on Windows Server 2012 R2 Standard

### ISSUE THREAD

**Issue by Dan-Ilan** [GoogleCloudPlatform/compute-image-windows#122]
Hey,
I'm trying to use activate_instance.ps1 to activate a Windows Server 2012 R2 Standard machine.
I get the following output:

```
Checking instance license activation status.
WIN-IKQRCC9Q6SQ needs to be activated by a KMS Server.
The variable '$get_product_details' cannot be retrieved because it has not 
been set.
At C:\Dan\activate_instance.ps1:184 
char:11
+           $get_product_details + '; no supported matches found for GCE.')
+           ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (get_product_details:String) [ 
   ], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined
 
Could not get the License Key for the instance. Activation skipped.
```
This is due to the fact that that on Windows 2012 R2 Standard, the following code 
`$script:product_name = (Get-ItemProperty -Path $reg -Name ProductName).ProductName`
Returns: `"Windows Server 2012 R2 Standard"`

While the switch that checks for Windows versions checks for `"Windows Server 2012 R2 Server Standard`". This fails the check and goes to the default clause, that has another bug with an unknown symbol `$get_product_details`

I haven't checked it for the Non-R2 version, but I suspect it's the same. Notice the two `"Server"` in string `"Windows Server 2012 Server Standard"`

Thanks
Dan

**Comment by adjackura** [comment]
Thanks for the PR to fix this. This is a bit of an odd area as we don't officially support anything other than 2008R2, 2012R2 and 2016 Datacenter. I'll merge your PR once you sign the CLA as it is a bug fix though.

**Comment by adjackura** [comment]
New google-compute-engine-sysprep package with fix is in staging repos, will be pushed to stable today or tomorrow.

**Comment by Dan-Ilan** [comment]
Thanks!
