### ISSUE TITLE
Please create windows_auth_go_example

### ISSUE THREAD

**Issue by discentem** [GoogleCloudPlatform/compute-image-windows#138]
It would be awesome to see an example using the API in Go, particularly for a tool like terraform.

**Comment by discentem** [comment]
So far I'm trying to just append basic values to the metadata but not having much luck. I can't quite tell if I successful (I think I'm getting a pending status). 

```go
val := "blarg"
  newMetadata := &compute.Metadata{
    Items:       []*compute.MetadataItems{{Key: "windows-keys", Value: &val}},
    Fingerprint: inst.Metadata.Fingerprint,
  }

  resp, err := computeService.Instances.SetMetadata(project, zone, instance, newMetadata).Context(ctx).Do()
  computeService.Instances.SetMetadata(project, zone, instance, newMetadata).Context(ctx).Do()
  checkError(err)
  fmt.Println(resp)

  inst2, err := computeService.Instances.Get(project, zone, instance).Context(ctx).Do()
  checkError(err)
  fmt.Println(inst2.Metadata)
```

**Comment by adjackura** [comment]
I'll spend some time today and see what I can come up with, at the very least I should be able to give you a rough example.

**Comment by discentem** [comment]
thank you @adjackura. very much appreciated.

**Comment by adjackura** [comment]
Example will be up on the docs page soon.
