### ISSUE TITLE
Ability to not shutdown during gcesysprep

### ISSUE THREAD

**Issue by MrLunar** [GoogleCloudPlatform/compute-image-windows#140]
Please can a `-NoShutdown` switch (or similar) be added to `sysprep.ps1` which will [prevent the shutdown](https://github.com/GoogleCloudPlatform/compute-image-windows/blob/f0e2733ef4c48ae8725aaaea8c1576cb5e7ab7b2/sysprep/sysprep.ps1#L169) occurring at the end of the script.

When using tools like [packer](https://www.packer.io/docs/builders/googlecompute.html), we'll run `gcesysprep` during the provisioning phase but since the instance will already have been shutdown, the attempt to shutdown by packer will fail the whole build.

AWS added a similar switch to resolve the same issue with their sysprep process: https://david-obrien.net/2016/12/packer-and-aws-windows-server-2016/#update-11072017

**Comment by adjackura** [comment]
New packages should be pushed next week.
