### ISSUE TITLE
GCESysprep can't shut down the machine on Windows Server version 1803

### ISSUE THREAD

**Issue by philwo** [GoogleCloudPlatform/compute-image-windows#154]
When running gcesysprep.bat on Windows Server version 1803, the machine doesn't shut down at the end. Here's the log from the serial console:

```
2018/09/05 17:07:15 GCESysprep: Beginning GCESysprep.
2018/09/05 17:07:15 GCESysprep: No answer file was specified. Using default file.
2018/09/05 17:07:15 GCESysprep: Running 'schtasks' with arguments '/delete /tn GCEStartup /f'
2018/09/05 17:07:15 GCESysprep: --> SUCCESS: The scheduled task "GCEStartup" was successfully deleted.
2018/09/05 17:07:15 GCESysprep: Clearing events in EventViewer.
2018/09/05 17:07:17 GCESysprep: Running 'C:\Windows\System32\Sysprep\sysprep.exe' with arguments '/generalize /oobe /quit /unattend:C:\Program Files\Google\Compute Engine\sysprep\unattended.xml'
2018/09/05 17:07:38 GCESysprep: Waiting for sysprep to complete.
2018/09/05 17:07:38 GCESysprep: Setting new startup command.
2018/09/05 17:07:38 GCESysprep: Forgetting persistent disks.
2018/09/05 17:07:38 GCESysprep: Clearing self signed certs.
2018/09/05 17:07:38 GCESysprep: Shutting down.
2018/09/05 17:07:38 GCESysprep: Running 'shutdown' with arguments '/s /t 00 /d p:2:4'
2018/09/05 17:07:38 GCESysprep: The machine is locked and cannot be shut down without the force option.(1271) {Line: 333 :   $out = &$Executable $Arguments 2>&1 | Out-String
, HResult: -2146233087, Script: C:\Program Files\Google\Compute Engine\sysprep\gce_base.psm1}
```

Looks like we have to pass something like "/f" to the shutdown command?

**Comment by adjackura** [comment]
That's very interesting, can you explain the steps you used to get this error? Our tests are working fine, but those are not run interactively so there may be a difference.

**Comment by philwo** [comment]
@adjackura Indeed we run our setup script interactively, so maybe that's the difference?

What we do is the following:
- We create a simple instance for imaging purposes from the windows-1803-core image. (Link)[https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/create_images.py#L123]. The instance is started with a startup script that simply dumps our actual (setup PowerShell script)[https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/setup-windows.ps1] to `C:\setup.ps1`.
- We wait until the VM is ready and the startup script ran, then RDP into it semi-automatically with Microsoft Remote Desktop for Mac. (Link)[https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/create_images.py#L148]
- Then we run the setup script by manually typing "powershell C:\setup" into the terminal. As a last step, the setup script sets up a (RunOnce registry entry to call gcesysprep.bat)[https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/setup-windows.ps1#L336] and reboots the machine.
- When the machine rebooted, we RDP into it again to trigger execution of the RunOnce script. You can see the GCESysPrep tool showing its progress bar as it does its work, then you're forcefully logged out (Remote Desktop shows an error that the connection was terminated).
- However, you can observe in the serial console log (as copied above) that the machine doesn't shutdown and instead prints the "The machine is locked and cannot be shut down" message.
- Shutting down the VM by clicking the "Stop" button for the VM in the Cloud Console lets it shut down cleanly and our imaging process completes.
