### ISSUE TITLE
URL parser does not trim query string when determining file type.

### ISSUE THREAD

**Issue by appnojag** [GoogleCloudPlatform/compute-image-windows#165]
When using a signed URL to initialize the metadata script URL, I get the following error:

ERROR: error getting script type from url path...

Looking at the code on metadata_scripts/GCEMetadataScripts/main.go:125:

	case url:
		trimmed := strings.TrimSpace(ms.Script)
		sType := trimmed[len(trimmed)-3:]
		var c *exec.Cmd
		dir, err := ioutil.TempDir("", "metadata-scripts")

The only grooming on the URL path is to trim whitespace then look at the last 4 chars of the raw URL to determine the filename suffix. Signed URLs contain query strings that the object store service uses to establish authentication, so the file name is not at the end of the URL.

If you want to infer the file type from the file suffix in a URL path you need to parse the URL and remove the query string contents ie, anything after the "?".

**Comment by adjackura** [comment]
Downloading if signed URLs will be a bit more complicated, the basic parsing in the agent does wont handle these situations correctly, I'll need to make the URL parsing much more robust.
