### ISSUE TITLE
activate_instance.ps1 fails to read Unlicensed status from Windows server

### ISSUE THREAD

**Issue by Pradu4422** [GoogleCloudPlatform/compute-image-windows#211]
Have some windows server 2008 R2 Enterprise images where License status is Unlicensed. The problem we are seeing is that activate_instance.ps1 doesn't read exact Licensed string leading to skip windows License activation. While verifying server is already Licensed,  function is returning true even the License status is Unlicensed. 

Can we update in Verify-ActivationStatus function for exact match for Licensed string to solve the issue?

**Comment by bkatyl** [comment]
Thanks for raising this issues. 

In looking at https://docs.microsoft.com/en-us/previous-versions/windows/desktop/sppwmi/softwarelicensingproduct, specifically LicenseStatus, it looks like the current logic works for values 2-6, but 0 and 1 will both match the current logic where as only 1 should match.

Value | Description
-- | --
0 | Unlicensed
1 | Licensed
2 | OOBGrace
3 | OOTGrace
4 | NonGenuineGrace
5 | Notification
6 | ExtendedGrace

I'll create a PR to make sure it also addresses having a value of "Unlicensed".
